Clusters:
  - name: "Cluster1"
    token: ""
    node_cpu_utilisation: "https://prometheus-k8s-openshift-monitoring.apps.Cluster1.tcs.turkcell.tgc/api/v1/query?query=instance:node_cpu_utilisation:rate1m"
    node_memory_utilisation: "https://prometheus-k8s-openshift-monitoring.apps.Cluster1.tcs.turkcell.tgc/api/v1/query?query=instance:node_memory_utilisation:ratio"
    node_network_receive_bytes_excluding_lo: "https://prometheus-k8s-openshift-monitoring.apps.Cluster1.tcs.turkcell.tgc/api/v1/query?query=instance:node_network_receive_bytes_excluding_lo:rate1m"
    node_disk_io_time_seconds_total: "https://prometheus-k8s-openshift-monitoring.apps.Cluster1.tcs.turkcell.tgc/api/v1/query?query=node_disk_io_time_seconds_total"
  - name: "Cluster2"
    token: ""
    node_cpu_utilisation: "https://prometheus-k8s-openshift-monitoring.apps.Cluster2.tcs.turkcell.tgc/api/v1/query?query=instance:node_cpu_utilisation:rate1m"
    node_memory_utilisation: "https://prometheus-k8s-openshift-monitoring.apps.Cluster2.tcs.turkcell.tgc/api/v1/query?query=instance:node_memory_utilisation:ratio"
    node_network_receive_bytes_excluding_lo: "https://prometheus-k8s-openshift-monitoring.apps.Cluster2.tcs.turkcell.tgc/api/v1/query?query=instance:node_network_receive_bytes_excluding_lo:rate1m"
    node_disk_io_time_seconds_total: "https://prometheus-k8s-openshift-monitoring.apps.Cluster2.tcs.turkcell.tgc/api/v1/query?query=node_disk_io_time_seconds_total"
  - name: "Cluster3"
    token: ""
    node_cpu_utilisation: "https://prometheus-k8s-openshift-monitoring.apps.Cluster3.tcs.turkcell.tgc/api/v1/query?query=instance:node_cpu_utilisation:rate1m"
    node_memory_utilisation: "https://prometheus-k8s-openshift-monitoring.apps.Cluster3.tcs.turkcell.tgc/api/v1/query?query=instance:node_memory_utilisation:ratio"
    node_network_receive_bytes_excluding_lo: "https://prometheus-k8s-openshift-monitoring.apps.Cluster3.tcs.turkcell.tgc/api/v1/query?query=instance:node_network_receive_bytes_excluding_lo:rate1m"
    node_disk_io_time_seconds_total: "https://prometheus-k8s-openshift-monitoring.apps.Cluster3.tcs.turkcell.tgc/api/v1/query?query=node_disk_io_time_seconds_total"
  - name: "Cluster4"
    token: ""
    node_cpu_utilisation: "https://prometheus-k8s-openshift-monitoring.apps.Cluster4.tcs.turkcell.tgc/api/v1/query?query=instance:node_cpu_utilisation:rate1m"
    node_memory_utilisation: "https://prometheus-k8s-openshift-monitoring.apps.Cluster4.tcs.turkcell.tgc/api/v1/query?query=instance:node_memory_utilisation:ratio"
    node_network_receive_bytes_excluding_lo: "https://prometheus-k8s-openshift-monitoring.apps.Cluster4.tcs.turkcell.tgc/api/v1/query?query=instance:node_network_receive_bytes_excluding_lo:rate1m"
    node_disk_io_time_seconds_total: "https://prometheus-k8s-openshift-monitoring.apps.Cluster4.tcs.turkcell.tgc/api/v1/query?query=node_disk_io_time_seconds_total"
  - name: "Cluster5"
    token: ""
    node_cpu_utilisation: "https://prometheus-k8s-openshift-monitoring.apps.Cluster5.tcs.turkcell.tgc/api/v1/query?query=instance:node_cpu_utilisation:rate1m"
    node_memory_utilisation: "https://prometheus-k8s-openshift-monitoring.apps.Cluster5.tcs.turkcell.tgc/api/v1/query?query=instance:node_memory_utilisation:ratio"
    node_network_receive_bytes_excluding_lo: "https://prometheus-k8s-openshift-monitoring.apps.Cluster5.tcs.turkcell.tgc/api/v1/query?query=instance:node_network_receive_bytes_excluding_lo:rate1m"
    node_disk_io_time_seconds_total: "https://prometheus-k8s-openshift-monitoring.apps.Cluster5.tcs.turkcell.tgc/api/v1/query?query=node_disk_io_time_seconds_total"
  - name: "Cluster6"
    token: ""
    node_cpu_utilisation: "https://prometheus-k8s-openshift-monitoring.apps.Cluster6.tcs.turkcell.tgc/api/v1/query?query=instance:node_cpu_utilisation:rate1m"
    node_memory_utilisation: "https://prometheus-k8s-openshift-monitoring.apps.Cluster6.tcs.turkcell.tgc/api/v1/query?query=instance:node_memory_utilisation:ratio"
    node_network_receive_bytes_excluding_lo: "https://prometheus-k8s-openshift-monitoring.apps.Cluster6.tcs.turkcell.tgc/api/v1/query?query=instance:node_network_receive_bytes_excluding_lo:rate1m"
    node_disk_io_time_seconds_total: "https://prometheus-k8s-openshift-monitoring.apps.Cluster6.tcs.turkcell.tgc/api/v1/query?query=node_disk_io_time_seconds_total"
  - name: "Cluster7"
    token: ""
    node_cpu_utilisation: "https://prometheus-k8s-openshift-monitoring.apps.Cluster7.tcs.turkcell.tgc/api/v1/query?query=instance:node_cpu_utilisation:rate1m"
    node_memory_utilisation: "https://prometheus-k8s-openshift-monitoring.apps.Cluster7.tcs.turkcell.tgc/api/v1/query?query=instance:node_memory_utilisation:ratio"
    node_network_receive_bytes_excluding_lo: "https://prometheus-k8s-openshift-monitoring.apps.Cluster7.tcs.turkcell.tgc/api/v1/query?query=instance:node_network_receive_bytes_excluding_lo:rate1m"
    node_disk_io_time_seconds_total: "https://prometheus-k8s-openshift-monitoring.apps.Cluster7.tcs.turkcell.tgc/api/v1/query?query=node_disk_io_time_seconds_total"

influxdb:
  Url: "xx.xx.xx.xx"
  Port: xx
  Measurement: "clusters"
  Database: "openshift"
  RetentionPolicy: "autogen"
